ALTER TABLE public.predictions
ADD COLUMN IF NOT EXISTS reference_price NUMERIC,
ADD COLUMN IF NOT EXISTS reference_time TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS final_price NUMERIC,
ADD COLUMN IF NOT EXISTS outcome TEXT,
ADD COLUMN IF NOT EXISTS evaluation_time TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS data_source TEXT;
